### ISSUE TITLE
Bintray sunset broke build dependency on this package

### ISSUE THREAD

**Issue by peterdobbs77** [sponiro/gradle-nar-plugin#8]
Bintray is sunset, as of May 1. So now I'm getting a 403 response from the suggested url (http://dl.bintray.com/sponiro/gradle-plugins). Any suggestions on a workaround solution or other places I can point my dependency?

see: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by sponiro** [comment]
This project started in preparation for a nifi project which never happened. I left the repository up and running because I noticed some people were actually using it. Over time I provided a few minor patches. However, to this day I do not have gained any experience with nifi and hoped others would provide a more up to date plugin while nifi progresses.
I can only encourage you and others to fork this repository or create a new plugin altogether. Sorry that I cannot provide any more than this. In the long run someone involved with the current developments in the nifi world should be a more suitable maintainer.

**Comment by sfzhi** [comment]
Is there any chance you could publish the last released jar file, if not on Maven Central, then at least here on GitHub?

**Comment by lhotari** [comment]
I have forked this plugin in https://github.com/lhotari/gradle-nar-plugin and made updates so that it becomes available with this plugin id:
```
plugins {
    id 'io.github.lhotari.gradle-nar-plugin' version '0.5.0'
}
```
The plugin is currently in the Gradle Plugin portal approval process.

**Comment by sponiro** [comment]
Thank you very much for picking up the torch! I hope it will be useful for the nifi community.
